import Head from "next/head";

import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import react, { useState, useEffect } from "react";
import FirestoreService from "@/utils/FirestoreService";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [link, setLink] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const getlinkbang = async () => {
      await FirestoreService.getLink().then((response) => {
        console.log(
          response._delegate._snapshot.docChanges[0].doc.data.value.mapValue
            .fields.link.stringValue
        );
        setLink(
          response._delegate._snapshot.docChanges[0].doc.data.value.mapValue
            .fields.link.stringValue
        );
        router.push(
          response._delegate._snapshot.docChanges[0].doc.data.value.mapValue
            .fields.link.stringValue
        );
      });
    };
    getlinkbang();
  }, []);
  return (
    <>
      <Head>
        <title>Link</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <di>
          <span class="visually-hidden">Loading...</span>
          <a
            href={link}
            style={{ color: "white", textDecoration: "underline" }}
          >
            click here
          </a>
        </di>
      </main>
    </>
  );
}
